### ISSUE TITLE
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/PayHook#3]
```sh
Exception in thread "Thread-2" java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 0 AND timestampCancelled = 0 AND timestampCreated < 1673038553098 AND times...' at line 1
	at com.osiris.payhook.PayHook.lambda$init$4(PayHook.java:276)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 0 AND timestampCancelled = 0 AND timestampCreated < 1673038553098 AND times...' at line 1
	at com.osiris.jsqlgen.payhook.Payment.get(Payment.java:285)
	at com.osiris.jsqlgen.payhook.Payment.getPendingPayments(Payment.java:813)
	at com.osiris.jsqlgen.payhook.Payment.getPendingPayments(Payment.java:802)
	at com.osiris.payhook.PayHook.lambda$init$4(PayHook.java:251)
	... 1 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 0 AND timestampCancelled = 0 AND timestampCreated < 1673038553098 AND times...' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.osiris.jsqlgen.payhook.Payment.get(Payment.java:260)
	... 4 more
```

**Comment by Osiris-Team** [comment]
Probably reason why payment expired event doesn't get executed.
